const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const SET_INGREDIENT = 'SET_INGREDIENT';
const FETCH_INGREDIENT_FAIL = 'FETCH_INGREDIENT_FAIL';


export {
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    SET_INGREDIENT,
    FETCH_INGREDIENT_FAIL
}
