const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const SET_INGREDIENT = 'SET_INGREDIENT';
const FETCH_INGREDIENT_FAIL = 'FETCH_INGREDIENT_FAIL';

const SET_ORDER_SUCESS = 'SET_ORDER_SUCESS';
const SET_ORDER_FAIL='SET_ORDER_FAIL';
const SET_ORDER_START='SET_ORDER_START';

const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL';
const FETCH_ORDER_START='FETCH_ORDER_START';

const INIT_PURCHASING = 'INIT_PURCHASING';



export {
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    SET_INGREDIENT,
    FETCH_INGREDIENT_FAIL,
    SET_ORDER_SUCESS,
    SET_ORDER_FAIL,
    SET_ORDER_START,
    INIT_PURCHASING,
    FETCH_ORDER_SUCCESS,
    FETCH_ORDER_FAIL,
    FETCH_ORDER_START
}
